services:
  postgres:
    image: postgis/postgis:18-3.6-alpine
    container_name: falzo-postgresql
    restart: unless-stopped
    networks:
      - falzo
    env_file: ./be/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - falzo
    env_file: ./be/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:latest
    container_name: falzo-redis
    restart: unless-stopped
    networks:
      - falzo
    env_file: ./be/.env
    ports:
      - "6379:6379"
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: falzo-seaweedfs
    networks:
      - falzo
    command: server -dir=/data -filer
    env_file: ./be/.env
    ports:
      - "8888:8888"
    expose:
      - "9333"
    volumes:
      - seaweedfs_data:/data
  api:
    build:
      context: ./be
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - falzo
    env_file: ./be/.env
    environment:
      SEAWEEDFS_BASE_URL: http://seaweedfs:8888
      SEAWEEDFS_PUBLIC_URL: https://image.falzo.life
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres
      - redis
      - mongodb
      - seaweedfs
  nginx:
    container_name: falzo-nginx
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: /api
    restart: unless-stopped
    networks:
      - falzo
    env_file: ./be/.env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./be/nginx/default.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - api
      - seaweedfs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  dozzle:
    image: amir20/dozzle:latest
    container_name: falzo-dozzle
    restart: unless-stopped
    networks:
      - falzo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle_data:/data
    ports:
      - "127.0.0.1:8080:8080"
networks:
  falzo:
    driver: bridge

volumes:
  postgres_data:
  redis:
  mongo_data:
  seaweedfs_data:
  dozzle_data:
