services:
  nginx:
    volumes:
      - ./be/nginx/default.bootstrap.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
