services:
    postgres:
      image: postgres:18
      container_name: app-postgres
      restart: unless-stopped

      environment:
        POSTGRES_DB: falzo_game_db
        POSTGRES_USER: falzo_user
        POSTGRES_PASSWORD: 0339540824Sson@

      ports:
        - "5432:5432"

      volumes:
        - postgres_data:/var/lib/postgresql/data

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
        interval: 5s
        timeout: 5s
        retries: 10
    redis:
      image: redis:alpine
      container_name: app_redis
      restart: unless-stopped
      enviroment:
        REDIS_PASSWORD: 0339540824Sson@
        command:
              [
                "redis-server",
                "--appendonly",
                "yes",
                "--requirepass",
                "${REDIS_PASSWORD}"
              ]
      ports:
          - "6379:6379"




      volumes:
          - redis_data:/data

      healthcheck:
          test:
              [
                "CMD-SHELL",
                "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"
              ]
          interval: 5s
          timeout: 3s
          retries: 10
          start_period: 5s

volumes:
    postgres_data:
    redis_data:
