CREATE TABLE undercover_word_pairs (
    id BIGSERIAL PRIMARY KEY,
    common_word VARCHAR(80) NOT NULL,
    different_word VARCHAR(80) NOT NULL,
    category VARCHAR(20) NOT NULL,
    language_code VARCHAR(10) NOT NULL DEFAULT 'en',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT undercover_word_pairs_common_not_blank
        CHECK (length(trim(common_word)) > 0),
    CONSTRAINT undercover_word_pairs_different_not_blank
        CHECK (length(trim(different_word)) > 0),
    CONSTRAINT undercover_word_pairs_words_different
        CHECK (lower(trim(common_word)) <> lower(trim(different_word))),
    CONSTRAINT undercover_word_pairs_category_valid
        CHECK (category IN (
            'adjective', 'verb', 'noun', 'phrase',
            'animal', 'plant', 'object', 'food', 'drink',
            'vehicle', 'place', 'profession', 'sport',
            'technology', 'nature', 'clothing', 'body',
            'school', 'household'
        )),
    CONSTRAINT undercover_word_pairs_language_valid
        CHECK (language_code IN ('en', 'vi'))
);

CREATE UNIQUE INDEX undercover_word_pairs_words_unique
    ON undercover_word_pairs (
        language_code,
        lower(trim(common_word)),
        lower(trim(different_word))
    );

CREATE INDEX undercover_word_pairs_active_idx
    ON undercover_word_pairs (language_code, category)
    WHERE is_active = TRUE;

ALTER TABLE room_rounds
    ADD COLUMN word_pair_id BIGINT REFERENCES undercover_word_pairs(id);

INSERT INTO undercover_word_pairs (
    common_word,
    different_word,
    category,
    language_code
) VALUES
    ('Big', 'Large', 'adjective', 'en'),
    ('Small', 'Tiny', 'adjective', 'en'),
    ('Fast', 'Quick', 'adjective', 'en'),
    ('Smart', 'Clever', 'adjective', 'en'),
    ('Happy', 'Joyful', 'adjective', 'en'),
    ('Angry', 'Furious', 'adjective', 'en'),
    ('Calm', 'Peaceful', 'adjective', 'en'),
    ('Quiet', 'Silent', 'adjective', 'en'),
    ('Brave', 'Courageous', 'adjective', 'en'),
    ('Honest', 'Truthful', 'adjective', 'en'),
    ('Easy', 'Simple', 'adjective', 'en'),
    ('Hard', 'Difficult', 'adjective', 'en'),
    ('Beautiful', 'Pretty', 'adjective', 'en'),
    ('Rich', 'Wealthy', 'adjective', 'en'),
    ('Safe', 'Secure', 'adjective', 'en'),
    ('Strange', 'Unusual', 'adjective', 'en'),
    ('Tired', 'Exhausted', 'adjective', 'en'),
    ('Afraid', 'Scared', 'adjective', 'en'),
    ('Correct', 'Accurate', 'adjective', 'en'),
    ('Empty', 'Vacant', 'adjective', 'en'),
    ('Begin', 'Start', 'verb', 'en'),
    ('End', 'Finish', 'verb', 'en'),
    ('Help', 'Assist', 'verb', 'en'),
    ('Buy', 'Purchase', 'verb', 'en'),
    ('Choose', 'Select', 'verb', 'en'),
    ('Build', 'Construct', 'verb', 'en'),
    ('Fix', 'Repair', 'verb', 'en'),
    ('Show', 'Display', 'verb', 'en'),
    ('Hide', 'Conceal', 'verb', 'en'),
    ('Ask', 'Inquire', 'verb', 'en'),
    ('Answer', 'Respond', 'verb', 'en'),
    ('Need', 'Require', 'verb', 'en'),
    ('Keep', 'Retain', 'verb', 'en'),
    ('Change', 'Modify', 'verb', 'en'),
    ('Use', 'Utilize', 'verb', 'en'),
    ('Try', 'Attempt', 'verb', 'en'),
    ('Leave', 'Depart', 'verb', 'en'),
    ('Get', 'Obtain', 'verb', 'en'),
    ('Make', 'Create', 'verb', 'en'),
    ('Check', 'Verify', 'verb', 'en'),
    ('Gift', 'Present', 'noun', 'en'),
    ('Job', 'Occupation', 'noun', 'en'),
    ('Error', 'Mistake', 'noun', 'en'),
    ('Goal', 'Objective', 'noun', 'en'),
    ('Chance', 'Opportunity', 'noun', 'en'),
    ('Trip', 'Journey', 'noun', 'en'),
    ('Story', 'Tale', 'noun', 'en'),
    ('Reply', 'Response', 'noun', 'en'),
    ('Idea', 'Concept', 'noun', 'en'),
    ('Friend', 'Companion', 'noun', 'en'),
    ('Look after', 'Take care of', 'phrase', 'en'),
    ('Find out', 'Discover', 'phrase', 'en'),
    ('Put off', 'Postpone', 'phrase', 'en'),
    ('Carry on', 'Continue', 'phrase', 'en'),
    ('Give up', 'Quit', 'phrase', 'en'),
    ('Set up', 'Arrange', 'phrase', 'en'),
    ('Point out', 'Highlight', 'phrase', 'en'),
    ('Think over', 'Consider', 'phrase', 'en'),
    ('Run into', 'Encounter', 'phrase', 'en'),
    ('Deal with', 'Handle', 'phrase', 'en'),
    ('Lớn', 'To lớn', 'adjective', 'vi'),
    ('Nhỏ', 'Bé', 'adjective', 'vi'),
    ('Nhanh', 'Mau', 'adjective', 'vi'),
    ('Thông minh', 'Lanh lợi', 'adjective', 'vi'),
    ('Vui vẻ', 'Hân hoan', 'adjective', 'vi'),
    ('Tức giận', 'Giận dữ', 'adjective', 'vi'),
    ('Bình tĩnh', 'Điềm tĩnh', 'adjective', 'vi'),
    ('Yên tĩnh', 'Im lặng', 'adjective', 'vi'),
    ('Dũng cảm', 'Can đảm', 'adjective', 'vi'),
    ('Trung thực', 'Thật thà', 'adjective', 'vi'),
    ('Dễ dàng', 'Đơn giản', 'adjective', 'vi'),
    ('Khó khăn', 'Gian nan', 'adjective', 'vi'),
    ('Xinh đẹp', 'Đẹp đẽ', 'adjective', 'vi'),
    ('Giàu có', 'Sung túc', 'adjective', 'vi'),
    ('An toàn', 'Bảo đảm', 'adjective', 'vi'),
    ('Kỳ lạ', 'Khác thường', 'adjective', 'vi'),
    ('Mệt mỏi', 'Kiệt sức', 'adjective', 'vi'),
    ('Sợ hãi', 'Lo sợ', 'adjective', 'vi'),
    ('Chính xác', 'Đúng đắn', 'adjective', 'vi'),
    ('Trống rỗng', 'Bỏ trống', 'adjective', 'vi'),
    ('Bắt đầu', 'Khởi đầu', 'verb', 'vi'),
    ('Kết thúc', 'Hoàn tất', 'verb', 'vi'),
    ('Giúp đỡ', 'Hỗ trợ', 'verb', 'vi'),
    ('Mua', 'Mua sắm', 'verb', 'vi'),
    ('Lựa chọn', 'Chọn lựa', 'verb', 'vi'),
    ('Xây dựng', 'Kiến tạo', 'verb', 'vi'),
    ('Sửa chữa', 'Khắc phục', 'verb', 'vi'),
    ('Hiển thị', 'Trình bày', 'verb', 'vi'),
    ('Che giấu', 'Ẩn giấu', 'verb', 'vi'),
    ('Hỏi', 'Thắc mắc', 'verb', 'vi'),
    ('Trả lời', 'Phản hồi', 'verb', 'vi'),
    ('Cần', 'Yêu cầu', 'verb', 'vi'),
    ('Giữ', 'Duy trì', 'verb', 'vi'),
    ('Thay đổi', 'Điều chỉnh', 'verb', 'vi'),
    ('Sử dụng', 'Dùng', 'verb', 'vi'),
    ('Thử', 'Cố gắng', 'verb', 'vi'),
    ('Rời đi', 'Khởi hành', 'verb', 'vi'),
    ('Nhận được', 'Thu được', 'verb', 'vi'),
    ('Tạo ra', 'Làm ra', 'verb', 'vi'),
    ('Kiểm tra', 'Xác minh', 'verb', 'vi'),
    ('Quà tặng', 'Món quà', 'noun', 'vi'),
    ('Công việc', 'Nghề nghiệp', 'noun', 'vi'),
    ('Lỗi', 'Sai sót', 'noun', 'vi'),
    ('Mục tiêu', 'Đích đến', 'noun', 'vi'),
    ('Cơ hội', 'Dịp', 'noun', 'vi'),
    ('Chuyến đi', 'Hành trình', 'noun', 'vi'),
    ('Câu chuyện', 'Truyện kể', 'noun', 'vi'),
    ('Lời đáp', 'Phản hồi', 'noun', 'vi'),
    ('Ý tưởng', 'Khái niệm', 'noun', 'vi'),
    ('Bạn bè', 'Bạn đồng hành', 'noun', 'vi'),
    ('Chăm sóc', 'Trông nom', 'phrase', 'vi'),
    ('Tìm ra', 'Khám phá', 'phrase', 'vi'),
    ('Trì hoãn', 'Hoãn lại', 'phrase', 'vi'),
    ('Tiếp tục', 'Duy trì', 'phrase', 'vi'),
    ('Từ bỏ', 'Bỏ cuộc', 'phrase', 'vi'),
    ('Thiết lập', 'Sắp xếp', 'phrase', 'vi'),
    ('Chỉ ra', 'Nhấn mạnh', 'phrase', 'vi'),
    ('Suy xét', 'Cân nhắc', 'phrase', 'vi'),
    ('Vô tình gặp', 'Chạm mặt', 'phrase', 'vi'),
    ('Giải quyết', 'Xử lý', 'phrase', 'vi'),
    ('Cat', 'Dog', 'animal', 'en'),
    ('Lion', 'Tiger', 'animal', 'en'),
    ('Rabbit', 'Hamster', 'animal', 'en'),
    ('Dolphin', 'Whale', 'animal', 'en'),
    ('Eagle', 'Hawk', 'animal', 'en'),
    ('Duck', 'Goose', 'animal', 'en'),
    ('Sheep', 'Goat', 'animal', 'en'),
    ('Horse', 'Donkey', 'animal', 'en'),
    ('Butterfly', 'Dragonfly', 'animal', 'en'),
    ('Frog', 'Toad', 'animal', 'en'),
    ('Rose', 'Tulip', 'plant', 'en'),
    ('Pine tree', 'Bamboo', 'plant', 'en'),
    ('Mango tree', 'Guava tree', 'plant', 'en'),
    ('Lotus', 'Water lily', 'plant', 'en'),
    ('Cactus', 'Aloe vera', 'plant', 'en'),
    ('Sunflower', 'Daisy', 'plant', 'en'),
    ('Mint', 'Basil', 'plant', 'en'),
    ('Rice', 'Wheat', 'plant', 'en'),
    ('Fern', 'Moss', 'plant', 'en'),
    ('Orchid', 'Lily', 'plant', 'en'),
    ('Spoon', 'Fork', 'object', 'en'),
    ('Cup', 'Water bottle', 'object', 'en'),
    ('Chair', 'Stool', 'object', 'en'),
    ('Pen', 'Pencil', 'object', 'en'),
    ('Phone', 'Tablet', 'object', 'en'),
    ('Wall clock', 'Watch', 'object', 'en'),
    ('Key', 'Lock', 'object', 'en'),
    ('Backpack', 'Suitcase', 'object', 'en'),
    ('Fan', 'Air conditioner', 'object', 'en'),
    ('Umbrella', 'Raincoat', 'object', 'en'),
    ('Mèo', 'Chó', 'animal', 'vi'),
    ('Sư tử', 'Hổ', 'animal', 'vi'),
    ('Thỏ', 'Chuột hamster', 'animal', 'vi'),
    ('Cá heo', 'Cá voi', 'animal', 'vi'),
    ('Đại bàng', 'Diều hâu', 'animal', 'vi'),
    ('Vịt', 'Ngỗng', 'animal', 'vi'),
    ('Cừu', 'Dê', 'animal', 'vi'),
    ('Ngựa', 'Lừa', 'animal', 'vi'),
    ('Bướm', 'Chuồn chuồn', 'animal', 'vi'),
    ('Ếch', 'Cóc', 'animal', 'vi'),
    ('Hoa hồng', 'Hoa tulip', 'plant', 'vi'),
    ('Cây thông', 'Cây tre', 'plant', 'vi'),
    ('Cây xoài', 'Cây ổi', 'plant', 'vi'),
    ('Hoa sen', 'Hoa súng', 'plant', 'vi'),
    ('Xương rồng', 'Nha đam', 'plant', 'vi'),
    ('Hoa hướng dương', 'Cúc họa mi', 'plant', 'vi'),
    ('Bạc hà', 'Húng quế', 'plant', 'vi'),
    ('Lúa gạo', 'Lúa mì', 'plant', 'vi'),
    ('Dương xỉ', 'Rêu', 'plant', 'vi'),
    ('Hoa lan', 'Hoa ly', 'plant', 'vi'),
    ('Muỗng', 'Nĩa', 'object', 'vi'),
    ('Cốc', 'Bình nước', 'object', 'vi'),
    ('Ghế tựa', 'Ghế đẩu', 'object', 'vi'),
    ('Bút mực', 'Bút chì', 'object', 'vi'),
    ('Điện thoại', 'Máy tính bảng', 'object', 'vi'),
    ('Đồng hồ treo tường', 'Đồng hồ đeo tay', 'object', 'vi'),
    ('Chìa khóa', 'Ổ khóa', 'object', 'vi'),
    ('Balo', 'Vali', 'object', 'vi'),
    ('Quạt', 'Máy lạnh', 'object', 'vi'),
    ('Ô', 'Áo mưa', 'object', 'vi'),
    ('Pizza', 'Burger', 'food', 'en'),
    ('Rice', 'Noodles', 'food', 'en'),
    ('Bread', 'Cake', 'food', 'en'),
    ('Chicken', 'Duck', 'food', 'en'),
    ('Beef', 'Pork', 'food', 'en'),
    ('Soup', 'Porridge', 'food', 'en'),
    ('Egg', 'Cheese', 'food', 'en'),
    ('Sushi', 'Kimbap', 'food', 'en'),
    ('Sandwich', 'Hot dog', 'food', 'en'),
    ('Ice cream', 'Yogurt', 'food', 'en'),
    ('Coffee', 'Tea', 'drink', 'en'),
    ('Milk', 'Soy milk', 'drink', 'en'),
    ('Orange juice', 'Apple juice', 'drink', 'en'),
    ('Cola', 'Lemonade', 'drink', 'en'),
    ('Beer', 'Wine', 'drink', 'en'),
    ('Smoothie', 'Milkshake', 'drink', 'en'),
    ('Water', 'Mineral water', 'drink', 'en'),
    ('Coconut water', 'Sugarcane juice', 'drink', 'en'),
    ('Hot chocolate', 'Cocoa', 'drink', 'en'),
    ('Green tea', 'Black tea', 'drink', 'en'),
    ('Car', 'Truck', 'vehicle', 'en'),
    ('Bus', 'Coach', 'vehicle', 'en'),
    ('Bicycle', 'Motorbike', 'vehicle', 'en'),
    ('Train', 'Subway', 'vehicle', 'en'),
    ('Airplane', 'Helicopter', 'vehicle', 'en'),
    ('Boat', 'Ship', 'vehicle', 'en'),
    ('Taxi', 'Ride-share car', 'vehicle', 'en'),
    ('Van', 'Minibus', 'vehicle', 'en'),
    ('Scooter', 'Electric bike', 'vehicle', 'en'),
    ('Ambulance', 'Fire truck', 'vehicle', 'en'),
    ('School', 'University', 'place', 'en'),
    ('Hospital', 'Clinic', 'place', 'en'),
    ('Market', 'Supermarket', 'place', 'en'),
    ('Hotel', 'Hostel', 'place', 'en'),
    ('Park', 'Garden', 'place', 'en'),
    ('Beach', 'Swimming pool', 'place', 'en'),
    ('Restaurant', 'Cafe', 'place', 'en'),
    ('Library', 'Bookstore', 'place', 'en'),
    ('Airport', 'Train station', 'place', 'en'),
    ('Museum', 'Art gallery', 'place', 'en'),
    ('Doctor', 'Nurse', 'profession', 'en'),
    ('Teacher', 'Lecturer', 'profession', 'en'),
    ('Police officer', 'Security guard', 'profession', 'en'),
    ('Chef', 'Baker', 'profession', 'en'),
    ('Engineer', 'Architect', 'profession', 'en'),
    ('Farmer', 'Gardener', 'profession', 'en'),
    ('Driver', 'Pilot', 'profession', 'en'),
    ('Singer', 'Actor', 'profession', 'en'),
    ('Journalist', 'Writer', 'profession', 'en'),
    ('Designer', 'Artist', 'profession', 'en'),
    ('Football', 'Basketball', 'sport', 'en'),
    ('Tennis', 'Badminton', 'sport', 'en'),
    ('Swimming', 'Diving', 'sport', 'en'),
    ('Running', 'Cycling', 'sport', 'en'),
    ('Volleyball', 'Handball', 'sport', 'en'),
    ('Boxing', 'Wrestling', 'sport', 'en'),
    ('Golf', 'Baseball', 'sport', 'en'),
    ('Skiing', 'Snowboarding', 'sport', 'en'),
    ('Yoga', 'Pilates', 'sport', 'en'),
    ('Chess', 'Go', 'sport', 'en'),
    ('Laptop', 'Desktop computer', 'technology', 'en'),
    ('Keyboard', 'Mouse', 'technology', 'en'),
    ('Website', 'Mobile app', 'technology', 'en'),
    ('Email', 'Text message', 'technology', 'en'),
    ('Camera', 'Camcorder', 'technology', 'en'),
    ('Robot', 'Drone', 'technology', 'en'),
    ('Wi-Fi', 'Bluetooth', 'technology', 'en'),
    ('Password', 'PIN', 'technology', 'en'),
    ('Server', 'Database', 'technology', 'en'),
    ('Headphones', 'Speaker', 'technology', 'en'),
    ('Mountain', 'Hill', 'nature', 'en'),
    ('River', 'Stream', 'nature', 'en'),
    ('Ocean', 'Lake', 'nature', 'en'),
    ('Forest', 'Jungle', 'nature', 'en'),
    ('Rain', 'Snow', 'nature', 'en'),
    ('Thunder', 'Lightning', 'nature', 'en'),
    ('Sun', 'Moon', 'nature', 'en'),
    ('Cloud', 'Fog', 'nature', 'en'),
    ('Island', 'Peninsula', 'nature', 'en'),
    ('Volcano', 'Earthquake', 'nature', 'en'),
    ('Shirt', 'T-shirt', 'clothing', 'en'),
    ('Pants', 'Shorts', 'clothing', 'en'),
    ('Dress', 'Skirt', 'clothing', 'en'),
    ('Jacket', 'Coat', 'clothing', 'en'),
    ('Shoes', 'Sandals', 'clothing', 'en'),
    ('Hat', 'Cap', 'clothing', 'en'),
    ('Socks', 'Gloves', 'clothing', 'en'),
    ('Belt', 'Tie', 'clothing', 'en'),
    ('Scarf', 'Shawl', 'clothing', 'en'),
    ('Pajamas', 'Uniform', 'clothing', 'en'),
    ('Hand', 'Foot', 'body', 'en'),
    ('Arm', 'Leg', 'body', 'en'),
    ('Eye', 'Ear', 'body', 'en'),
    ('Nose', 'Mouth', 'body', 'en'),
    ('Finger', 'Toe', 'body', 'en'),
    ('Head', 'Neck', 'body', 'en'),
    ('Chest', 'Back', 'body', 'en'),
    ('Heart', 'Lung', 'body', 'en'),
    ('Tooth', 'Tongue', 'body', 'en'),
    ('Hair', 'Skin', 'body', 'en'),
    ('Book', 'Notebook', 'school', 'en'),
    ('Pen', 'Eraser', 'school', 'en'),
    ('Ruler', 'Protractor', 'school', 'en'),
    ('Blackboard', 'Whiteboard', 'school', 'en'),
    ('Classroom', 'Laboratory', 'school', 'en'),
    ('Homework', 'Exam', 'school', 'en'),
    ('Student', 'Teacher', 'school', 'en'),
    ('Lesson', 'Lecture', 'school', 'en'),
    ('Backpack', 'Pencil case', 'school', 'en'),
    ('Diploma', 'Certificate', 'school', 'en'),
    ('Bed', 'Sofa', 'household', 'en'),
    ('Table', 'Desk', 'household', 'en'),
    ('Refrigerator', 'Freezer', 'household', 'en'),
    ('Washing machine', 'Dishwasher', 'household', 'en'),
    ('Broom', 'Mop', 'household', 'en'),
    ('Plate', 'Bowl', 'household', 'en'),
    ('Pot', 'Pan', 'household', 'en'),
    ('Lamp', 'Flashlight', 'household', 'en'),
    ('Door', 'Window', 'household', 'en'),
    ('Blanket', 'Pillow', 'household', 'en'),
    ('Pizza', 'Bánh hamburger', 'food', 'vi'),
    ('Cơm', 'Mì', 'food', 'vi'),
    ('Bánh mì', 'Bánh ngọt', 'food', 'vi'),
    ('Thịt gà', 'Thịt vịt', 'food', 'vi'),
    ('Thịt bò', 'Thịt heo', 'food', 'vi'),
    ('Canh', 'Cháo', 'food', 'vi'),
    ('Trứng', 'Phô mai', 'food', 'vi'),
    ('Sushi', 'Kimbap', 'food', 'vi'),
    ('Bánh sandwich', 'Xúc xích', 'food', 'vi'),
    ('Kem', 'Sữa chua', 'food', 'vi'),
    ('Cà phê', 'Trà', 'drink', 'vi'),
    ('Sữa bò', 'Sữa đậu nành', 'drink', 'vi'),
    ('Nước cam', 'Nước táo', 'drink', 'vi'),
    ('Nước ngọt', 'Nước chanh', 'drink', 'vi'),
    ('Bia', 'Rượu vang', 'drink', 'vi'),
    ('Sinh tố', 'Sữa lắc', 'drink', 'vi'),
    ('Nước lọc', 'Nước khoáng', 'drink', 'vi'),
    ('Nước dừa', 'Nước mía', 'drink', 'vi'),
    ('Sô-cô-la nóng', 'Ca cao', 'drink', 'vi'),
    ('Trà xanh', 'Trà đen', 'drink', 'vi'),
    ('Ô tô', 'Xe tải', 'vehicle', 'vi'),
    ('Xe buýt', 'Xe khách', 'vehicle', 'vi'),
    ('Xe đạp', 'Xe máy', 'vehicle', 'vi'),
    ('Tàu hỏa', 'Tàu điện ngầm', 'vehicle', 'vi'),
    ('Máy bay', 'Trực thăng', 'vehicle', 'vi'),
    ('Thuyền', 'Tàu thủy', 'vehicle', 'vi'),
    ('Taxi', 'Xe công nghệ', 'vehicle', 'vi'),
    ('Xe tải nhỏ', 'Xe buýt nhỏ', 'vehicle', 'vi'),
    ('Xe tay ga', 'Xe đạp điện', 'vehicle', 'vi'),
    ('Xe cứu thương', 'Xe cứu hỏa', 'vehicle', 'vi'),
    ('Trường học', 'Đại học', 'place', 'vi'),
    ('Bệnh viện', 'Phòng khám', 'place', 'vi'),
    ('Chợ', 'Siêu thị', 'place', 'vi'),
    ('Khách sạn', 'Nhà nghỉ', 'place', 'vi'),
    ('Công viên', 'Khu vườn', 'place', 'vi'),
    ('Bãi biển', 'Hồ bơi', 'place', 'vi'),
    ('Nhà hàng', 'Quán cà phê', 'place', 'vi'),
    ('Thư viện', 'Nhà sách', 'place', 'vi'),
    ('Sân bay', 'Ga tàu', 'place', 'vi'),
    ('Bảo tàng', 'Phòng tranh', 'place', 'vi'),
    ('Bác sĩ', 'Y tá', 'profession', 'vi'),
    ('Giáo viên', 'Giảng viên', 'profession', 'vi'),
    ('Cảnh sát', 'Bảo vệ', 'profession', 'vi'),
    ('Đầu bếp', 'Thợ làm bánh', 'profession', 'vi'),
    ('Kỹ sư', 'Kiến trúc sư', 'profession', 'vi'),
    ('Nông dân', 'Người làm vườn', 'profession', 'vi'),
    ('Tài xế', 'Phi công', 'profession', 'vi'),
    ('Ca sĩ', 'Diễn viên', 'profession', 'vi'),
    ('Nhà báo', 'Nhà văn', 'profession', 'vi'),
    ('Nhà thiết kế', 'Họa sĩ', 'profession', 'vi'),
    ('Bóng đá', 'Bóng rổ', 'sport', 'vi'),
    ('Quần vợt', 'Cầu lông', 'sport', 'vi'),
    ('Bơi lội', 'Lặn', 'sport', 'vi'),
    ('Chạy bộ', 'Đạp xe', 'sport', 'vi'),
    ('Bóng chuyền', 'Bóng ném', 'sport', 'vi'),
    ('Quyền anh', 'Đấu vật', 'sport', 'vi'),
    ('Đánh gôn', 'Bóng chày', 'sport', 'vi'),
    ('Trượt tuyết', 'Trượt ván tuyết', 'sport', 'vi'),
    ('Yoga', 'Pilates', 'sport', 'vi'),
    ('Cờ vua', 'Cờ vây', 'sport', 'vi'),
    ('Máy tính xách tay', 'Máy tính để bàn', 'technology', 'vi'),
    ('Bàn phím', 'Chuột máy tính', 'technology', 'vi'),
    ('Trang web', 'Ứng dụng di động', 'technology', 'vi'),
    ('Email', 'Tin nhắn', 'technology', 'vi'),
    ('Máy ảnh', 'Máy quay', 'technology', 'vi'),
    ('Rô-bốt', 'Máy bay không người lái', 'technology', 'vi'),
    ('Wi-Fi', 'Bluetooth', 'technology', 'vi'),
    ('Mật khẩu', 'Mã PIN', 'technology', 'vi'),
    ('Máy chủ', 'Cơ sở dữ liệu', 'technology', 'vi'),
    ('Tai nghe', 'Loa', 'technology', 'vi'),
    ('Núi', 'Đồi', 'nature', 'vi'),
    ('Sông', 'Suối', 'nature', 'vi'),
    ('Đại dương', 'Hồ', 'nature', 'vi'),
    ('Rừng', 'Rừng nhiệt đới', 'nature', 'vi'),
    ('Mưa', 'Tuyết', 'nature', 'vi'),
    ('Sấm', 'Chớp', 'nature', 'vi'),
    ('Mặt trời', 'Mặt trăng', 'nature', 'vi'),
    ('Mây', 'Sương mù', 'nature', 'vi'),
    ('Hòn đảo', 'Bán đảo', 'nature', 'vi'),
    ('Núi lửa', 'Động đất', 'nature', 'vi'),
    ('Áo sơ mi', 'Áo thun', 'clothing', 'vi'),
    ('Quần dài', 'Quần short', 'clothing', 'vi'),
    ('Váy liền', 'Chân váy', 'clothing', 'vi'),
    ('Áo khoác ngắn', 'Áo khoác dài', 'clothing', 'vi'),
    ('Giày', 'Dép', 'clothing', 'vi'),
    ('Mũ vành', 'Mũ lưỡi trai', 'clothing', 'vi'),
    ('Tất', 'Găng tay', 'clothing', 'vi'),
    ('Thắt lưng', 'Cà vạt', 'clothing', 'vi'),
    ('Khăn quàng', 'Khăn choàng', 'clothing', 'vi'),
    ('Đồ ngủ', 'Đồng phục', 'clothing', 'vi'),
    ('Bàn tay', 'Bàn chân', 'body', 'vi'),
    ('Cánh tay', 'Chân', 'body', 'vi'),
    ('Mắt', 'Tai', 'body', 'vi'),
    ('Mũi', 'Miệng', 'body', 'vi'),
    ('Ngón tay', 'Ngón chân', 'body', 'vi'),
    ('Đầu', 'Cổ', 'body', 'vi'),
    ('Ngực', 'Lưng', 'body', 'vi'),
    ('Tim', 'Phổi', 'body', 'vi'),
    ('Răng', 'Lưỡi', 'body', 'vi'),
    ('Tóc', 'Da', 'body', 'vi'),
    ('Sách', 'Vở', 'school', 'vi'),
    ('Bút', 'Cục tẩy', 'school', 'vi'),
    ('Thước kẻ', 'Thước đo góc', 'school', 'vi'),
    ('Bảng đen', 'Bảng trắng', 'school', 'vi'),
    ('Lớp học', 'Phòng thí nghiệm', 'school', 'vi'),
    ('Bài tập về nhà', 'Bài kiểm tra', 'school', 'vi'),
    ('Học sinh', 'Giáo viên', 'school', 'vi'),
    ('Bài học', 'Bài giảng', 'school', 'vi'),
    ('Cặp sách', 'Hộp bút', 'school', 'vi'),
    ('Bằng tốt nghiệp', 'Chứng chỉ', 'school', 'vi'),
    ('Giường', 'Ghế sofa', 'household', 'vi'),
    ('Bàn ăn', 'Bàn làm việc', 'household', 'vi'),
    ('Tủ lạnh', 'Tủ đông', 'household', 'vi'),
    ('Máy giặt', 'Máy rửa chén', 'household', 'vi'),
    ('Chổi', 'Cây lau nhà', 'household', 'vi'),
    ('Đĩa', 'Bát', 'household', 'vi'),
    ('Nồi', 'Chảo', 'household', 'vi'),
    ('Đèn bàn', 'Đèn pin', 'household', 'vi'),
    ('Cửa ra vào', 'Cửa sổ', 'household', 'vi'),
    ('Chăn', 'Gối', 'household', 'vi');
