// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"be/internal/api"
	"be/internal/api/handler"
	"be/internal/api/middleware"
	authapp "be/internal/application/auth"
	chatapp "be/internal/application/chat"
	roomapp "be/internal/application/room"
	"be/internal/application/social"
	"be/internal/config"
	"context"
)

// Injectors from wire.go:

func initializeApplication(ctx context.Context, cfg *config.Config) (*application, func(), error) {
	metrics := provideMetrics()
	logger, cleanup, err := provideLogger(cfg, metrics)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup2, err := provideDatabase(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := provideRedis(ctx, cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthHandler := provideHealthHandler(pool, client)
	passwordHasher := providePasswordHasher()
	userRepository := provideUserRepository(pool)
	tokenManager, err := provideTokenManager(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tokenSessionStore := provideTokenSessionStore(client, cfg)
	clock := provideClock()
	registerUseCase := authapp.NewRegisterUseCase(passwordHasher, userRepository, tokenManager, tokenSessionStore, clock)
	loginUseCase := provideLoginUseCase(passwordHasher, userRepository, tokenManager, tokenSessionStore, cfg, clock)
	refreshTokenUseCase := authapp.NewRefreshTokenUseCase(userRepository, tokenManager, tokenSessionStore, clock)
	forgotPasswordUseCase := authapp.NewForgotPasswordUseCase(userRepository, tokenManager, tokenSessionStore, clock)
	resetPasswordUseCase := authapp.NewResetPasswordUseCase(userRepository, passwordHasher, tokenManager, tokenSessionStore, clock)
	logoutUseCase := authapp.NewLogoutUseCase(tokenManager, tokenSessionStore, clock)
	googleIdentityVerifier := provideGoogleIdentityVerifier(cfg)
	googleLoginUseCase := authapp.NewGoogleLoginUseCase(googleIdentityVerifier, userRepository, tokenManager, tokenSessionStore, clock)
	authHandler := provideAuthHandler(registerUseCase, loginUseCase, refreshTokenUseCase, forgotPasswordUseCase, resetPasswordUseCase, logoutUseCase, logger, googleLoginUseCase, cfg)
	repository := provideRoomRepository(pool)
	inviteCodeGenerator := provideInviteCodeGenerator()
	createRoomUseCase := provideCreateRoomUseCase(repository, inviteCodeGenerator, clock, cfg)
	listRoomsUseCase := roomapp.NewListRoomsUseCase(repository)
	getRoomUseCase := roomapp.NewGetRoomUseCase(repository)
	joinRoomUseCase := roomapp.NewJoinRoomUseCase(repository)
	kickMemberUseCase := roomapp.NewKickMemberUseCase(repository)
	dealRoundUseCase := roomapp.NewDealRoundUseCase(repository, clock)
	getCurrentCardUseCase := roomapp.NewGetCurrentCardUseCase(repository)
	updateDiscussionUseCase := roomapp.NewUpdateDiscussionUseCase(repository)
	getRoundStateUseCase := roomapp.NewGetRoundStateUseCase(repository, clock)
	castVoteUseCase := roomapp.NewCastVoteUseCase(repository, clock)
	playerReadyUseCase := roomapp.NewPlayerReadyUseCase(repository, clock)
	finishTurnUseCase := roomapp.NewFinishTurnUseCase(repository, clock)
	mrWhiteGuessUseCase := roomapp.NewMrWhiteGuessUseCase(repository, clock)
	backplane := provideRealtimeBackplane(client, cfg, logger, metrics)
	chatportsRepository := provideChatRepository(pool)
	service := chatapp.NewService(chatportsRepository)
	hub := provideRealtimeHub(clock, backplane, logger, metrics, service)
	roomHandler := handler.NewRoomHandler(createRoomUseCase, listRoomsUseCase, getRoomUseCase, joinRoomUseCase, kickMemberUseCase, dealRoundUseCase, getCurrentCardUseCase, updateDiscussionUseCase, getRoundStateUseCase, castVoteUseCase, playerReadyUseCase, finishTurnUseCase, mrWhiteGuessUseCase, hub, logger)
	realtimeHandler := provideRealtimeHandler(getRoomUseCase, getRoundStateUseCase, hub, logger, metrics, cfg)
	chatHandler := handler.NewChatHandler(service, getRoomUseCase, logger)
	socialRepository := provideSocialRepository(pool)
	socialService := social.NewService(socialRepository, clock)
	socialHandler := handler.NewSocialHandler(socialService, logger, hub)
	authenticator := middleware.NewAuthenticator(tokenManager)
	httpHandler := provideMetricsHandler()
	mux := api.NewRouter(healthHandler, authHandler, roomHandler, realtimeHandler, chatHandler, socialHandler, authenticator, httpHandler, logger)
	server := provideHTTPServer(cfg, mux)
	phaseTransitionHandler := providePhaseTransitionHandler(hub, getRoomUseCase, logger)
	phaseScheduler := roomapp.NewPhaseScheduler(repository, clock, metrics, logger, phaseTransitionHandler)
	mainApplication := &application{
		logger:         logger,
		server:         server,
		realtimeHub:    hub,
		phaseScheduler: phaseScheduler,
	}
	return mainApplication, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
