package domainroom

import "errors"

var (
	ErrRoomNotFound           = errors.New("room not found")
	ErrRoomNameRequired       = errors.New("room name is required")
	ErrRoomNameTooLong        = errors.New("room name must be at most 80 characters")
	ErrInvalidRoomID          = errors.New("invalid room id")
	ErrInvalidHostUserID      = errors.New("invalid host user id")
	ErrInvalidInviteCode      = errors.New("invalid invite code")
	ErrInvalidMaxPlayers      = errors.New("invalid maximum players")
	ErrInvalidLanguageCode    = errors.New("room language must be en or vi")
	ErrInvalidRoomExpiration  = errors.New("invalid room expiration")
	ErrInviteCodeConflict     = errors.New("invite code already exists")
	ErrInviteCodeUnavailable  = errors.New("could not allocate an invite code")
	ErrRoomFull               = errors.New("room is full")
	ErrRoomNotWaiting         = errors.New("room is not waiting for players")
	ErrNotRoomHost            = errors.New("only the room host can perform this action")
	ErrRoomMemberNotFound     = errors.New("room member not found")
	ErrInvalidRoomMemberID    = errors.New("invalid room member id")
	ErrCannotKickSelf         = errors.New("room host cannot remove themselves")
	ErrNotEnoughPlayers       = errors.New("at least four players are required to start a game")
	ErrRoundCardNotFound      = errors.New("round card not found")
	ErrWordPairNotFound       = errors.New("no active word pair found")
	ErrInvalidDiscussionTime  = errors.New("description time must be between 10 and 30 seconds")
	ErrRoundInProgress        = errors.New("the current round must finish before starting another round")
	ErrVotingNotOpen          = errors.New("voting is not open yet")
	ErrVotingCompleted        = errors.New("voting has already completed")
	ErrAlreadyVoted           = errors.New("player has already voted")
	ErrInvalidVoteTarget      = errors.New("vote target must be another room member")
	ErrPlayerEliminated       = errors.New("eliminated players can only spectate")
	ErrInvalidGameState       = errors.New("action is not allowed in the current game state")
	ErrNotCurrentTurn         = errors.New("only the current player can finish this turn")
	ErrPlayerAlreadyReady     = errors.New("player already confirmed the role card")
	ErrMrWhiteGuessNotAllowed = errors.New("mr. white guess is not allowed")
	ErrMrWhiteAlreadyGuessed  = errors.New("mr. white has already guessed")
)
