export const travelPins = [
  {
    id: "highland-morning",
    imageId: "mu-cang-chai-dawn",
    location: "Mu Cang Chai, Vietnam",
    height: "h-[360px]",
    gradient: "bg-[linear-gradient(145deg,#f7d36e,#8dc871_48%,#346c42)]",
    mapX: 72,
    mapY: 43,
  },
  {
    id: "island-blue",
    imageId: "ly-son-coast",
    location: "Ly Son, Vietnam",
    height: "h-[470px]",
    gradient: "bg-[linear-gradient(145deg,#b9f3ff,#58a9d4_52%,#1f4a70)]",
    mapX: 70,
    mapY: 58,
  },
  {
    id: "lantern-street",
    imageId: "kyoto-lantern-night",
    location: "Kyoto, Japan",
    height: "h-[310px]",
    gradient: "bg-[linear-gradient(145deg,#ffd5a4,#e38a60_50%,#713d35)]",
    mapX: 78,
    mapY: 38,
  },
  {
    id: "alpine-lake",
    imageId: "swiss-lake-view",
    location: "Interlaken, Switzerland",
    height: "h-[520px]",
    gradient: "bg-[linear-gradient(145deg,#caffea,#64bbb3_50%,#1d5874)]",
    mapX: 48,
    mapY: 35,
  },
  {
    id: "turkiye-sunset",
    imageId: "istanbul-skyline",
    location: "Istanbul, Turkiye",
    height: "h-[390px]",
    gradient: "bg-[linear-gradient(145deg,#ffd8b1,#d58d50_50%,#62382e)]",
    mapX: 54,
    mapY: 43,
  },
  {
    id: "patagonia-path",
    imageId: "patagonia-trail",
    location: "Torres del Paine, Chile",
    height: "h-[450px]",
    gradient: "bg-[linear-gradient(145deg,#ddf4ff,#72acd2_52%,#264c70)]",
    mapX: 33,
    mapY: 76,
  },
  {
    id: "terrace-garden",
    imageId: "mu-cang-chai-dawn",
    location: "Sapa, Vietnam",
    height: "h-[420px]",
    gradient: "bg-[linear-gradient(145deg,#ffeaa4,#9ec96f_48%,#446f47)]",
    mapX: 71,
    mapY: 45,
  },
  {
    id: "coastal-quiet",
    imageId: "ly-son-coast",
    location: "Da Nang, Vietnam",
    height: "h-[330px]",
    gradient: "bg-[linear-gradient(145deg,#caf7ff,#6bbadd_50%,#2b5875)]",
    mapX: 72,
    mapY: 55,
  },
  {
    id: "old-town-glow",
    imageId: "kyoto-lantern-night",
    location: "Gion, Japan",
    height: "h-[480px]",
    gradient: "bg-[linear-gradient(145deg,#ffd9af,#d17a5c_50%,#593044)]",
    mapX: 79,
    mapY: 39,
  },
  {
    id: "lake-silence",
    imageId: "swiss-lake-view",
    location: "Lucerne, Switzerland",
    height: "h-[350px]",
    gradient: "bg-[linear-gradient(145deg,#ddfff0,#7fc6bf_50%,#38657c)]",
    mapX: 47,
    mapY: 36,
  },
  {
    id: "dome-horizon",
    imageId: "istanbul-skyline",
    location: "Galata, Turkiye",
    height: "h-[430px]",
    gradient: "bg-[linear-gradient(145deg,#ffe1bd,#c98255_52%,#523440)]",
    mapX: 53,
    mapY: 42,
  },
  {
    id: "wild-south",
    imageId: "patagonia-trail",
    location: "Aysen, Chile",
    height: "h-[300px]",
    gradient: "bg-[linear-gradient(145deg,#e3f6ff,#8ab7cf_48%,#344d63)]",
    mapX: 31,
    mapY: 74,
  },
] as const;

export type TravelPin = (typeof travelPins)[number];

export const exploreCollections = [
  "All",
  "Homes",
  "Travel",
  "Food",
  "Style",
  "Wellness",
  "Architecture",
  "Outdoors",
] as const;

export type ExploreCollection = (typeof exploreCollections)[number];

export const explorePins = [
  {
    id: "rice-terrace-light",
    imageId: "mu-cang-chai-dawn",
    title: "Morning terraces",
    author: "Nora Field",
    city: "Mu Cang Chai",
    collection: "Travel",
    saves: "18.4k",
    height: "h-[340px]",
    gradient: "bg-[linear-gradient(145deg,#f6d36b,#80b96e_50%,#2f6d51)]",
  },
  {
    id: "coastal-villa",
    imageId: "ly-son-coast",
    title: "Blue coast hideaway",
    author: "Casa Atelier",
    city: "Ly Son",
    collection: "Homes",
    saves: "9.7k",
    height: "h-[430px]",
    gradient: "bg-[linear-gradient(145deg,#95e4f6,#3f92c9_54%,#173d66)]",
  },
  {
    id: "lantern-dinner",
    imageId: "kyoto-lantern-night",
    title: "Lantern dinner room",
    author: "Mika Studio",
    city: "Kyoto",
    collection: "Food",
    saves: "12.1k",
    height: "h-[300px]",
    gradient: "bg-[linear-gradient(145deg,#ffd0a1,#d77a58_54%,#5e2f36)]",
  },
  {
    id: "lake-spa",
    imageId: "swiss-lake-view",
    title: "Lakehouse reset",
    author: "Alpine Edit",
    city: "Interlaken",
    collection: "Wellness",
    saves: "22.9k",
    height: "h-[470px]",
    gradient: "bg-[linear-gradient(145deg,#c7ffe6,#63b9b4_52%,#1f5c78)]",
  },
  {
    id: "sunset-domes",
    imageId: "istanbul-skyline",
    title: "Copper hour skyline",
    author: "Ayla Notes",
    city: "Istanbul",
    collection: "Architecture",
    saves: "7.6k",
    height: "h-[360px]",
    gradient: "bg-[linear-gradient(145deg,#ffd7ad,#d48a4d_54%,#623729)]",
  },
  {
    id: "patagonia-layer",
    imageId: "patagonia-trail",
    title: "Patagonia trail layers",
    author: "Wilder Co.",
    city: "Torres del Paine",
    collection: "Outdoors",
    saves: "15.8k",
    height: "h-[410px]",
    gradient: "bg-[linear-gradient(145deg,#d8f2ff,#6aa7d2_52%,#244c72)]",
  },
  {
    id: "linen-suite",
    imageId: "swiss-lake-view",
    title: "Quiet linen suite",
    author: "Room Service",
    city: "Lucerne",
    collection: "Style",
    saves: "6.3k",
    height: "h-[320px]",
    gradient: "bg-[linear-gradient(145deg,#f8f2e8,#c7d4cc_50%,#718986)]",
  },
  {
    id: "market-table",
    imageId: "kyoto-lantern-night",
    title: "Market table palette",
    author: "Supper Club",
    city: "Osaka",
    collection: "Food",
    saves: "10.2k",
    height: "h-[390px]",
    gradient: "bg-[linear-gradient(145deg,#ffddb5,#f09268_50%,#884437)]",
  },
  {
    id: "pool-edge",
    imageId: "ly-son-coast",
    title: "Pool edge afternoon",
    author: "Stay Index",
    city: "Da Nang",
    collection: "Homes",
    saves: "13.5k",
    height: "h-[450px]",
    gradient: "bg-[linear-gradient(145deg,#b6f2ff,#5aaed6_50%,#295b76)]",
  },
  {
    id: "glass-cabin",
    imageId: "patagonia-trail",
    title: "Glass cabin plans",
    author: "Northline",
    city: "Aysen",
    collection: "Architecture",
    saves: "8.9k",
    height: "h-[335px]",
    gradient: "bg-[linear-gradient(145deg,#e0f4ff,#8ab7ce_48%,#314a5f)]",
  },
  {
    id: "garden-breakfast",
    imageId: "mu-cang-chai-dawn",
    title: "Garden breakfast",
    author: "Soft Serve",
    city: "Sapa",
    collection: "Wellness",
    saves: "11.6k",
    height: "h-[380px]",
    gradient: "bg-[linear-gradient(145deg,#fff0a8,#91c777_50%,#3f7350)]",
  },
  {
    id: "evening-walk",
    imageId: "istanbul-skyline",
    title: "Evening walk edit",
    author: "Rumi Lane",
    city: "Galata",
    collection: "Travel",
    saves: "19.1k",
    height: "h-[485px]",
    gradient: "bg-[linear-gradient(145deg,#ffd9b8,#bd7654_52%,#51333f)]",
  },
] as const;
