apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falzo
  labels:
    app.kubernetes.io/name: falzo
    app.kubernetes.io/part-of: falzo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - falzo.life
      secretName: falzo-tls
  rules:
    - host: falzo.life
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: falzo-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: falzo-frontend
                port:
                  number: 3000
