apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falzo
resources:
  - job.yaml
images:
  - name: falzo/migrate
    newName: ghcr.io/your-org/falzo-migrate
    newTag: replace-me
