events{}

http {
    upstream api_backend {
        server app:8000;
    }
    server {


        # Server frontend
        location / {
            proxy_pass http://web:3000;
        }
        # API route
        listen 80;
        location /api/ {
            proxy_pass http://api_backend/;
        }
    }
}
